services:
  app:
    init: true
    restart: unless-stopped
    image: dex_app
    env_file: .env.prod
    networks:
      dex_network:
    ports:
      - 127.0.0.1:2006:2006
    volumes:
      - /run/mysqld/:/run/mysqld/:ro
    healthcheck:
      test: ["CMD", "/init", "--health"]
      interval: 30s
      timeout: 5s
      retries: 2
networks:
  dex_network:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.64.0/24
